"""first

Revision ID: e61ac08d718c
Revises: 
Create Date: 2019-07-21 18:46:30.184307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61ac08d718c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('babies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Pname', sa.Text(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toy_name', sa.Text(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys')
    op.drop_table('parents')
    op.drop_table('babies')
    # ### end Alembic commands ###
